import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import {
  appContainer,
  globalContent,
  globalNav,
  globalItem,
  globalTitle,
  globalMain,
} from "./global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={appContainer}>
          <h1 className={globalTitle}>Slack-Tify</h1>
          <div className={globalContent}>
            <nav className={globalNav}>
              <Link className={globalItem} href={"/"}>
                Home
              </Link>
              <Link className={globalItem} href={"/workspace"}>
                Channel
              </Link>
              <Link className={globalItem} href={"/dm"}>
                DM
              </Link>
              <Link className={globalItem} href={"/login"}>
                Login
              </Link>
            </nav>
            <main className={globalMain}>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
